version: "3.8"

services:
  unbound:
    build: unbound
    restart: always
    volumes:
      - ./root.hints:/usr/local/etc/unbound/root.hints:ro
    environment:
      - THREADS
      - SLABS
      - VIRTUAL_HOST
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
