version: "3.8"

services:
  unbound:
    image: dubhad/unbound:1.12.0
    environment:
      - THREADS
      - SLABS
      - CERT_NAME
      - KEY_NAME
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "853:853/tcp"
      - "853:853/udp"
      - "443:443/tcp"
    restart: always
    volumes:
      - ${ROOT_HINTS_FILE}:/usr/local/etc/unbound/root.hints:ro
      - ${CERTS_DIR}:/usr/local/etc/unbound/certs:ro
      - ${CONF_DIR}:/usr/local/etc/unbound/conf:ro
