version: "3.8"

services:
  unbound:
    build: unbound
    restart: always
    volumes:
      - ./root.hints:/usr/local/etc/unbound/root.hints:ro
      - ./certs/privkey.pem:/usr/local/etc/unbound/key.pem:ro
      - ./certs/fullchain.pem:/usr/local/etc/unbound/cert.pem:ro
    environment:
      - THREADS
      - SLABS
    ports:
        - "53:53/tcp"
        - "53:53/udp"
        - "443:443/tcp"
        - "443:443/udp"
        - "853:853/tcp"
        - "853:853/udp"
